// vue/todo/src/components/TodoList.vue
<script setup>
import { useTodoStore } from '@/stores/todo'
import TodoListItem from './TodoListItem.vue'

const todoStore = useTodoStore()
</script>
<template>
  <ul class="divide-y divide-gray-200">
    <TodoListItem v-for="todo in todoStore.todos" :key="todo.id" :todo="todo" />
  </ul>
</template>
<style></style>

// react-tailwind/todo_reducer/src/components/TodoList.tsx
import TodoListItem from "./TodoListItem";

export default function TodoList({
  todos,
  dispatch,
}: {
  todos: TodoItem[];
  dispatch: React.ActionDispatch<[action: TodoReducerAction]>;
}) {
  return (
    <ul className="divide-y divide-gray-200">
      {todos &&
        todos.map((todo) => {
          return <TodoListItem key={todo.id} dispatch={dispatch} todo={todo} />;
        })}
    </ul>
  );
}
