// vue/todo/src/components/Todo.vue
<script setup>
import TodoHeader from './TodoHeader.vue'
import TodoEditor from './TodoEditor.vue'
import TodoList from './TodoList.vue'
</script>
<template>
  <div class="max-w-md mx-auto overflow-hidden rounded-lg shadow-lg">
    <TodoHeader />
    <TodoEditor />
    <TodoList />
  </div>
</template>
<style scoped></style>

// react-tailwind/todo_reducer/src/components/Todo.tsx
import TodoEditor from "./TodoEditor";
import TodoHeader from "./TodoHeader";
import TodoList from "./TodoList";

export default function Todo() {
  return (
    <div className="w-[350px] max-w-md mx-auto shadow-lg rounded-lg overflow-hidden bg-white">
      <TodoHeader />
      <TodoEditor />
      <TodoList />
    </div>
  );
}
