// vue/todo/src/components/TodoListItem.vue
<script setup>
import { useTodoStore } from '@/stores/todo'

const props = defineProps({
  todo: {
    type: Object,
  },
})

const todoStore = useTodoStore()
const handleChange = () => {
  todoStore.toggleTodo(props.todo.id)
}
const handleDelete = () => {
  todoStore.deleteTodo(props.todo.id)
}
</script>
<template>
  <li class="flex items-center justify-between p-3 transition-colors border-b hover:bg-gray-100">
    <div class="flex items-center">
      <input
        type="checkbox"
        :class="`mr-3 h-4 w-4 text-blue-500 focus:ring-blue-400`"
        @checked="props.todo.done"
        @change="handleChange"
      />
      <span>{{ props.todo.text }}</span>
    </div>
    <button class="ml-4 text-red-500 hover:text-red-700" @click="handleDelete">Delete</button>
  </li>
</template>

// react-tailwind/todo_reducer/src/components/TodoListItem.tsx
import { ActionDispatch } from "react";

export default function TodoListItem({
  todo,
  dispatch,
}: {
  key: number;
  todo: TodoItem;
  dispatch: ActionDispatch<[action: TodoReducerAction]>;
}) {
  return (
    <li className="flex items-center justify-between p-3 border-b hover:bg-gray-100 transition-colors">
      <div className="flex items-center">
        <input
          type="checkbox"
          className="mr-3 h-4 w-4 text-blue-500 focus:ring-blue-400"
          onChange={() => dispatch({ type: "ToggleTodo", payload: todo.id })}
          checked={todo.done}
        />
        <label style={{ textDecoration: todo.done ? "line-through" : "" }}>
          {todo.text}
        </label>
      </div>
      <button
        className="text-red-500 hover:text-red-700 ml-4"
        onClick={() => dispatch({ type: "DeleteTodo", payload: todo.id })}
      >
        Delete
      </button>
    </li>
  );
}
